### ISSUE TITLE
Add autocompletion support for reference links

### ISSUE THREAD

**Issue by sethfowler** [microsoft/vscode-markdown-languageservice#127]
Today, you can autocomplete URL links. For example, typing this will trigger completion starting at "bar":

```md
[foo](##bar)
```

However, you currently can't autocomplete reference links. It would be great if you could do that, as well. In particular, in this example, completion should start at the first "bar":

```md
[foo][bar]

[bar]: ./bar.md#baz
```

This would make working with Markdown files that use reference links much easier.

**Comment by mjbvz** [comment]
Unless I've misunderstood, this already works:

![Screenshot 2023-03-21 at 1 57 28 PM](https://user-images.githubusercontent.com/12821956/226739136-253c96ba-d069-491f-8d6d-02fabb344f4c.png)

You may need to manually trigger the suggestions in this case though. In VS Code, you can use `ctrl+space` for this

**Comment by sethfowler** [comment]
@mjbvz Great, glad to hear the functionality is already in place!

Do you think it'd be reasonable to say that there is still an issue here, since the suggestions are not being triggered automatically? I didn't expect to need to trigger them automatically since they _are_ automatic for URL links. Is there something that prevents automatic suggestions in the reference link case?

**Comment by mjbvz** [comment]
This was a design decision. We don't auto show suggestions whenever you type `[` because you don't always want to create a reference link (or maybe you're typing the text of a reference link, not the reference. Ppopping up the suggest widget automatically in these instances could get annoying

**Comment by sethfowler** [comment]
@mjbvz Is it possible to take context into account? I can see why you wouldn't want to pop it up every time you press `[`, but it does make sense to pop it up on the second `[` in `[foo][` - at that point you're almost certainly typing the reference portion of a reference link. Even just doing it after `][` would eliminate most false positives, I'd think.

FWIW, I noticed a bug with the `ctrl+space` approach, as well. Pressing `ctrl+space` after `[foo][` pops up link reference suggestions, as expected. However, pressing `ctrl+space` after `[` does not. This prevents you from using suggestions to create a collapsed reference link (`[foo][]`) or shortcut reference link (`[foo]`).
