### ISSUE TITLE
Add markdown linter support and Improve markdown default theme

### ISSUE THREAD

**Issue by li1234yun** [microsoft/vscode-markdown-languageservice#16]
Hello,
Maybe you can consider to support markdown lint and default theme such as github markdown theme etc. It will be very useful.

[markdown linter](https://github.com/DavidAnson/vscode-markdownlint)
[markdown github theme](https://github.com/mjbvz/vscode-github-markdown-preview-style)
[markdown all in one](https://github.com/yzhang-gh/vscode-markdown)

I think you can include them in one plugin, because too many plugin are complex. It's just my advice!

**Comment by mjbvz** [comment]
Linting is out of scope for this library as there are already good markdown minting libraries out there
