### ISSUE TITLE
MD files don't always get marked dirty & don't always identify problems

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode-markdown-languageservice#45]
After initially filing this on [VSCode](https://github.com/microsoft/vscode/issues/158709), I'm refiling it here as I've only been able to reproduce on MD files, and consistently on the same files across machines. (in my case I'm using this primarily with my Obsidian vault... but I can duplicate all behavior with Obsidian closed, so it's not related to the syncing, or anything else in that app)

When I say "certain files" at the start of the next paragraph, I haven't noticed any pattern that would let me be more specific

For certain files, when the file is open, problems will not get yellow squiggles under them although they show int he problems list & the tab turns yellow. When this occurs, editing the document will not mark the file dirty, resulting in Save doing nothing. With a file in this state, closing & restarting VSCode will mark the file as dirty, but saving it will not mark the file as clean (unless the save is triggered by closing the dirty file). At that point restarting VSCode again will still show the file dirty even though it's saved. Saving here will result in a file conflict error from VSCode, although both versions are identical. If instead of saving the file, the file is Reverted, the file will then be marked clean again.

A side effect of this is that closing one of these dirty but unsaved files will result in the sidebar showing a count of dirty files that is greater than the number of dirty files open in tabs.

Some things I've tried, and their results...

- disabling all extensions: no effect... the problems went away since Markdownlint was off, but the same files still produced the same behavior
- deleting my %APPSETTINGS%/Code folder, except for the user settings json, keybindings json, and snippets... no effect
- opening a file that consistently reproduces this issue, and removing the problem area... get the file to save, restart VSCode, open the file, then restore the file contents to its original... that file now behaves correctly, consistently

I did pour through the logging in the VSCode Output window and the only error I saw was an unexpected null thrown from the changecase extension... ~~but it was showing in the MD language service logs even when I had that extension disabled (and yes, I had restarted)~~

if there's anything else I can copy-paste in here that might help isolate this, please let me know

**Comment by af4jm** [comment]
more info (hadn't noticed previously)... when a file is displaying the buggy behavior, links to that file from other files get a bogus red squiggle for a link to a file that doesn't exist

**Comment by mjbvz** [comment]
This should stay on the VS Code side for now since it talking about editor behavior. Sounds like it was already fixed in VS Code insiders though?

**Comment by af4jm** [comment]
this seems to be resolved in VSCode 1.72.0... files that consistently exhibited the strange behavior have been normal since that update
